/**
 * SINGLE SOURCE OF TRUTH for the archive.
 *
 * Publications mirror the event folders in /public/media/<event>/.
 *   - A folder with photos  -> a full publication (images live in
 *     /public/publications/<slug>/, generated by scripts/seed-assets.py).
 *   - An empty event folder  -> a "coming soon" publication (status:
 *     "coming-soon", no cover/gallery/pdf).
 *
 * To add or refill a publication: drop photos into /public/media/<event>/,
 * mirror them in scripts/seed-assets.py, run `npm run seed`, then add/update
 * one object below.
 */

export type PublicationCategory =
  | "Nürburgring"
  | "Le Mans"
  | "Formula 1"
  | "Hillclimb"
  | "GT Racing";

/** Canonical filter order. Filters render data-driven, in this order. */
export const CATEGORY_ORDER: PublicationCategory[] = [
  "Nürburgring",
  "Le Mans",
  "Formula 1",
  "Hillclimb",
  "GT Racing",
];

export type GallerySectionLabel =
  | "Arrival"
  | "Practice"
  | "Race"
  | "Night"
  | "Atmosphere"
  | "People"
  | "Details"
  | "Victory";

export interface GallerySection {
  label: GallerySectionLabel;
  /** Optional short editorial caption shown under the chapter title. */
  caption?: string;
  images: string[];
}

export type PublicationStatus = "published" | "coming-soon";

export interface Publication {
  slug: string;
  title: string;
  /** Explicit line breaks for the stacked cover title (defaults to splitting
   *  the title on spaces, e.g. keep "Le Mans" on one line). */
  coverTitle?: string[];
  /** CSS object-position for the cover crop, e.g. "25% 50%" to centre a subject. */
  coverPosition?: string;
  subtitle: string;
  location: string;
  category: PublicationCategory;
  date: string; // ISO, used for sorting; year derived for display
  dateLabel: string; // human display, e.g. "29 May – 1 June 2025"
  circuit: string;
  format: string;
  description: string;
  gallery: GallerySection[];
  /** Absent for "coming soon" editions. */
  cover?: string;
  pdf?: string;
  featured?: boolean;
  status?: PublicationStatus; // defaults to "published"
  pages?: number;
  photos?: string; // display string, e.g. "180+"
  /** Future-proofing: search / filtering / related. */
  tags?: string[];
}

const base = (slug: string) => `/publications/${slug}`;

export const publications: Publication[] = [
  {
    slug: "24h-nuerburgring-2025",
    title: "24H Nürburgring 2025",
    subtitle: "Four days. One track. Hundreds of stories.",
    location: "Nürburgring, Germany",
    category: "Nürburgring",
    date: "2025-06-19",
    dateLabel: "19 – 22 June 2025",
    circuit: "Nürburgring Nordschleife",
    format: "Digital Brochure",
    cover: `${base("24h-nuerburgring-2025")}/cover.jpg`,
    coverPosition: "25% 50%",
    pdf: `${base("24h-nuerburgring-2025")}/brochure.pdf`,
    description:
      "The 24-hour race at the Nürburgring is more than a race. It is a test of everything. Twenty-four hours through fog, rain and floodlight in the Eifel. This is our visual story.",
    featured: true,
    pages: 82,
    photos: "180+",
    tags: ["endurance", "nordschleife", "gt3", "night"],
    gallery: [
      {
        label: "Arrival",
        caption: "The beginning. Paddock, pit lane and the calm before.",
        images: [
          `${base("24h-nuerburgring-2025")}/gallery/01.jpg`,
          `${base("24h-nuerburgring-2025")}/gallery/02.jpg`,
          `${base("24h-nuerburgring-2025")}/gallery/03.jpg`,
        ],
      },
      {
        label: "Race",
        caption: "Twenty-four hours of intensity.",
        images: [
          `${base("24h-nuerburgring-2025")}/gallery/04.jpg`,
          `${base("24h-nuerburgring-2025")}/gallery/05.jpg`,
          `${base("24h-nuerburgring-2025")}/gallery/06.jpg`,
          `${base("24h-nuerburgring-2025")}/gallery/07.jpg`,
        ],
      },
      {
        label: "Night",
        caption: "Another world after dark.",
        images: [
          `${base("24h-nuerburgring-2025")}/gallery/08.jpg`,
          `${base("24h-nuerburgring-2025")}/gallery/09.jpg`,
        ],
      },
      {
        label: "Atmosphere",
        caption: "The mood of the Eifel.",
        images: [
          `${base("24h-nuerburgring-2025")}/gallery/10.jpg`,
          `${base("24h-nuerburgring-2025")}/gallery/11.jpg`,
          `${base("24h-nuerburgring-2025")}/gallery/12.jpg`,
          `${base("24h-nuerburgring-2025")}/gallery/13.jpg`,
          `${base("24h-nuerburgring-2025")}/gallery/14.jpg`,
          `${base("24h-nuerburgring-2025")}/gallery/15.jpg`,
        ],
      },
    ],
  },
  {
    slug: "f1-monza-2024",
    title: "F1 Monza 2024",
    subtitle: "The Temple of Speed.",
    location: "Monza, Italy",
    category: "Formula 1",
    date: "2024-08-30",
    dateLabel: "30 August – 1 September 2024",
    circuit: "Autodromo Nazionale Monza",
    format: "Digital Brochure",
    cover: `${base("f1-monza-2024")}/cover.jpg`,
    pdf: `${base("f1-monza-2024")}/brochure.pdf`,
    description:
      "Monza. The Temple of Speed. A weekend of slipstreams, late braking into the first chicane and the roar of the tifosi at the fastest circuit on the Formula 1 calendar.",
    pages: 48,
    photos: "70+",
    tags: ["formula-1", "monza", "grand-prix"],
    gallery: [
      {
        label: "Practice",
        caption: "Finding the limit at the Temple of Speed.",
        images: [
          `${base("f1-monza-2024")}/gallery/01.jpg`,
          `${base("f1-monza-2024")}/gallery/02.jpg`,
        ],
      },
      {
        label: "Race",
        caption: "Wheel to wheel down the straight.",
        images: [
          `${base("f1-monza-2024")}/gallery/03.jpg`,
          `${base("f1-monza-2024")}/gallery/04.jpg`,
        ],
      },
      {
        label: "Atmosphere",
        caption: "The colour of a Grand Prix weekend.",
        images: [
          `${base("f1-monza-2024")}/gallery/05.jpg`,
          `${base("f1-monza-2024")}/gallery/06.jpg`,
        ],
      },
    ],
  },
  {
    slug: "24h-le-mans-2026",
    title: "24H Le Mans 2026",
    coverTitle: ["24H", "Le Mans", "2026"],
    subtitle: "A century of speed down the Mulsanne.",
    location: "Le Mans, France",
    category: "Le Mans",
    date: "2026-06-13",
    dateLabel: "13 – 14 June 2026",
    circuit: "Circuit de la Sarthe",
    format: "Digital Brochure",
    cover: `${base("24h-le-mans-2026")}/cover.jpg`,
    pdf: `${base("24h-le-mans-2026")}/brochure.pdf`,
    description:
      "A century of speed down the Mulsanne. Hypercars and GT machinery through dusk, midnight and the long road to the finish at the greatest race in the world.",
    featured: true,
    pages: 56,
    photos: "60+",
    tags: ["endurance", "le-mans", "hypercar"],
    gallery: [
      {
        label: "Race",
        caption: "Hypercars at full chat.",
        images: [
          `${base("24h-le-mans-2026")}/gallery/01.jpg`,
          `${base("24h-le-mans-2026")}/gallery/02.jpg`,
        ],
      },
      {
        label: "Atmosphere",
        caption: "The Sarthe, in motion.",
        images: [`${base("24h-le-mans-2026")}/gallery/03.jpg`],
      },
    ],
  },
  {
    slug: "24h-nuerburgring-2024",
    title: "24H Nürburgring 2024",
    subtitle: "Golden light and a long night in the Eifel.",
    location: "Nürburgring, Germany",
    category: "Nürburgring",
    date: "2024-05-30",
    dateLabel: "30 May – 2 June 2024",
    circuit: "Nürburgring Nordschleife",
    format: "Digital Brochure",
    cover: "/media/optimized/main-1800/CK1A9919.JPG",
    coverPosition: "27% 50%",
    description:
      "Golden hour over the Nordschleife and a long night in the Eifel.",
    photos: "2",
    tags: ["endurance", "nordschleife", "gt3"],
    gallery: [
      {
        label: "Race",
        caption: "Through the Eifel.",
        images: [
          "/media/optimized/main-1800/CK1A9467.JPG",
          "/media/optimized/main-1800/CK1A9919.JPG",
        ],
      },
    ],
  },
  {
    slug: "24h-nuerburgring-2022",
    title: "24H Nürburgring 2022",
    subtitle: "Where the modern legend was written.",
    location: "Nürburgring, Germany",
    category: "Nürburgring",
    date: "2022-05-28",
    dateLabel: "28 – 29 May 2022",
    circuit: "Nürburgring Nordschleife",
    format: "Digital Brochure",
    description:
      "The return to a full-capacity Eifel classic. The full publication is in production.",
    status: "coming-soon",
    photos: "Coming soon",
    tags: ["endurance", "nordschleife", "gt3"],
    gallery: [],
  },
];
